from _typeshed import Incomplete

class New_Game:
    base_folder: str
    current_game: Incomplete
    game_types: Incomplete
    @classmethod
    def new_game(cls, game_name, networking: bool = False) -> None: ...

class SaveSystem:
    base_folder: str
    @classmethod
    def save_inventory(cls, game_name, inventory, filename: str = 'inventory.json') -> None: ...
    @classmethod
    def load_inventory(cls, game_name, inventory, filename: str = 'inventory.json') -> None: ...
    @classmethod
    def list_games(cls, list_games: bool = False, folders_path: str = 'database') -> None: ...

class debug_system:
    @staticmethod
    def debug(arg, *game_types, debug: bool = False) -> None: ...

class RAMManager:
    size: Incomplete
    mem: Incomplete
    offset: int
    index: Incomplete
    def __init__(self, size_kb: int) -> None: ...
    def store(self, key: str, data: bytes): ...
    def load(self, key): ...

class Behaviour:
    def awake(self) -> None: ...
    def start(self) -> None: ...
    def update(self, dt) -> None: ...
    def draw(self) -> None: ...

class GameLoop:
    objects: Incomplete
    running: bool
    started: bool
    target_fps: Incomplete
    debug: Incomplete
    def __init__(self, target_fps: int = 60, debug: bool = False) -> None: ...
    def log(self, *args) -> None: ...
    def add(self, obj) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
