from typing import Any, Dict, List

class New_Game:
    base_folder: str
    current_game: list | None
    game_types: dict[str, int]

    @classmethod
    def new_game(cls, game_name: str, networking: bool = False) -> None: ...


class SaveSystem:
    base_folder: str

    @classmethod
    def save_inventory(cls, game_name: str, inventory: Any, filename: str = ...) -> None: ...

    @classmethod
    def load_inventory(cls, game_name: str, inventory: Any, filename: str = ...) -> None: ...

    @classmethod
    def list_games(cls, list_games: bool = False, folders_path: str = ...) -> None: ...


class debug_system:
    @staticmethod
    def debug(arg: Any, *game_types: str, debug: bool = False) -> None: ...


class RAMManager:
    size: int
    offset: int
    index: Dict[str, tuple[int, int]]

    def __init__(self, size_kb: int) -> None: ...
    def store(self, key: str, data: bytes) -> None: ...
    def load(self, key: str) -> memoryview: ...


class Behaviour:
    def awake(self) -> None: ...
    def start(self) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self) -> None: ...
    def OPD2_start(self) -> None: ...
    def OPD2_loop(self) -> None: ...


class GameLoop:
    target_fps: int
    debug: bool

    def __init__(self, target_fps: int = 60, debug: bool = False) -> None: ...
    def add(self, obj: Any) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
