from typing import Any

class UIPrint:
    def print(self, *args: Any) -> None: ...
    def clear(self) -> None: ...

ui_print: UIPrint


class UIElement:
    visible: bool
    focusable: bool

    def draw(self, focused: bool = False) -> None: ...
    def handle_input(self, input_type: Any) -> None: ...


class Button(UIElement):
    def __init__(self, text: str, on_click: Any) -> None: ...


class Label(UIElement):
    def __init__(self, text: str) -> None: ...


class Scene:
    def __init__(self, name: str) -> None: ...
    def update(self, dt: float) -> None: ...


class SceneManager:
    def change_scene(self, scene: Scene) -> None: ...
    def update(self, dt: float) -> None: ...
    def feed_input(self, data: str) -> None: ...


class OPD2:
    width: int
    height: int

    def __init__(self, width: int, height: int, window_name: str) -> None: ...
    def begin_frame(self) -> None: ...
    def end_frame(self) -> None: ...
    def should_close(self) -> bool: ...
    def close(self) -> None: ...
    @staticmethod
    def poll_events() -> None: ...
    @staticmethod
    def terminate() -> None: ...
