from OpenGL.GL import *
from _typeshed import Incomplete

class UIPrint:
    buffer: Incomplete
    active_scene: Incomplete
    def __init__(self) -> None: ...
    def set_scene(self, scene) -> None: ...
    def print(self, *args, **kwargs) -> None: ...
    def get_buffer(self): ...
    def clear(self) -> None: ...

ui_print: Incomplete

class UIElement:
    visible: bool
    ui: Incomplete
    focusable: bool
    def __init__(self) -> None: ...
    def draw(self, focused: bool = False) -> None: ...
    def handle_input(self, input_type) -> None: ...

class Button(UIElement):
    text: Incomplete
    on_click: Incomplete
    focusable: bool
    def __init__(self, text, on_click) -> None: ...
    def draw(self, focused: bool = False) -> None: ...
    def handle_input(self, input_type) -> None: ...

class Label(UIElement):
    text: Incomplete
    def __init__(self, text) -> None: ...
    def draw(self, focused: bool = False) -> None: ...

class UIManager:
    elements: Incomplete
    focus_index: int
    dirty: bool
    input_buffer: Incomplete
    def __init__(self) -> None: ...
    def add(self, element) -> None: ...
    def update(self, dt) -> None: ...
    def move_focus(self, direction) -> None: ...
    def get_focused_element(self): ...
    def draw(self) -> None: ...
    def feed_input(self, input_str) -> None: ...

class Scene:
    name: Incomplete
    ui_manager: Incomplete
    def __init__(self, name) -> None: ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def update(self, dt) -> None: ...

class SceneManager:
    current_scene: Incomplete
    def __init__(self) -> None: ...
    def change_scene(self, scene: Scene): ...
    def update(self, dt) -> None: ...
    def feed_input(self, data) -> None: ...

def start_input_thread(scene_manager: SceneManager): ...

class OPD2:
    width: Incomplete
    height: Incomplete
    window_name: Incomplete
    background_color: Incomplete
    window: Incomplete
    def __init__(self, width, height, window_name) -> None: ...
    def begin_frame(self) -> None: ...
    def end_frame(self) -> None: ...
    def should_close(self): ...
    def terminate(self) -> None: ...
