class Inventory:
    items: dict[str, int]

    def __init__(self) -> None: ...
    def add_item(self, item_key: str, count: int = ...) -> bool: ...
    def set_item(self, item_key: str, count: int) -> bool: ...
