from _typeshed import Incomplete

class Inventory:
    items: Incomplete
    def __init__(self) -> None: ...
    def add_item(self, item_key: str, count: int = 1): ...
    def set_item(self, item_key: str, count: int): ...
