class Registry:
    items: dict[str, dict]

    @classmethod
    def register_item(cls, item_key: str, item_data: dict) -> None: ...
    @classmethod
    def get_item(cls, item_key: str) -> dict | None: ...
    @classmethod
    def has_item(cls, item_key: str) -> bool: ...
